# Generated by Django 3.2.5 on 2021-07-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0003_alter_box_name'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Package Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='box.box')),
                ('product', models.ManyToManyField(null=True, related_name='products', to='product.Product')),
            ],
        ),
    ]
