# Generated by Django 3.2.5 on 2021-07-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='box',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product',
        ),
    ]
