# Generated by Django 3.2.5 on 2021-07-28 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_packagerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 28, 8, 29, 25, 919387)),
            preserve_default=False,
        ),
    ]
