# Generated by Django 3.2.5 on 2021-07-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('package', '0004_packagerelation_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagerelation',
            name='product',
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ManyToManyField(null=True, related_name='products', to='product.Product'),
        ),
    ]
