# Generated by Django 3.2.5 on 2021-07-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.RemoveField(
            model_name='box',
            name='product',
        ),
    ]
