# Generated by Django 3.2.5 on 2021-07-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20210727_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Box Name'),
        ),
    ]
